### ISSUE TITLE
Spurious errors in testing on Firefox 21

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/riskmap#175]
Sometimes (50% ish of the time) firefox 21 on Browserstack fails with a script error, says React is not defined. Only happens when doing source coverage? Maybe we just need to go to a newer version of firefox?

**Comment by abrahamq** [comment]
Also happens even when source coverage is turned off.

**Comment by talltom** [comment]
Hi @abrahamq - is this one such bug?
https://travis-ci.org/urbanriskmap/petabencana.id/builds/208377040

**Comment by abrahamq** [comment]
I don't think so? That one looks like it broke on iOS? I restarted the build and it worked. I'm looking into this now. If it becomes a problem we disable browserstack on travis-ci and run the unit tests on chromium, which travis supports?

**Comment by talltom** [comment]
Testing currently disabled. Note front-end development moving to Angular.
