### ISSUE TITLE
need to transpile e2e tests

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/riskmap#179]
Right now I have end to end testing working, but if we want to write them in es6 then we have to transpile them, which means setting up a build process for this. This is complicated because our build system isn't the greatest (an unholy amalgamation of gulp and aurelia-cli). Here's something to build off of (HA!) https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-esnext/build/tasks/e2e.js

**Comment by talltom** [comment]
Front-end dev (and testing) moving to Angular, closing this Aurelia specific issue.
