### ISSUE TITLE
Make e2e tests work on browserstack 

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/riskmap#184]
For local: 

requires running the app, then running the BrowserStackLocal binary with your key, and putting browser.local in the capabilities of the protractor.config.js, in addition to the other configuration. Then this will cause browserstack to run the tests on the device specified in the config file, but hitting the server that is being run on your development machine. 

For travis: 
... going to need to run the app somewhere that browserstack can hit? Unclear about how to do this. 
There's an npm module browserstack-local that allows you to start the binary from javascript, and we can include it in our package.json. Then we'd also have to run au run from travis after building?

**Comment by talltom** [comment]
Front-end dev (and testing) moving to Angular, closing this issue.
