### ISSUE TITLE
Adding Semarang to Main Map

### ISSUE THREAD

**Issue by anexact** [urbanriskmap/riskmap#212]
FY17Ext Dev Meeting Field Office 03 _ MF & EH will meet with Semarang officials last week of August to determine what boundaries can be added within and adjacent to city; request for city of Semarang to be added to the existing three cities on landing page

**Comment by talltom** [comment]
This was fixed in b28773f553f80dce434855b8445b2cac3be1fad0 and awaits roll out to production.
