### ISSUE TITLE
Merge Reports and Legend tabs in Nav Bar

### ISSUE THREAD

**Issue by anexact** [urbanriskmap/riskmap#215]
FY17Ext Dev Meeting Field Office 06 _ in the Nav bar, request to combine Reports tab and legend to make it simpler to find for users; also, per previous issue, if the city to city navigation is enabled at the map level, the city selection buttons on the legend can be eliminated as well.

**Comment by talltom** [comment]
As described in #211 City to City navigation not an option.

Additionally, #218 will require further symbols to be added to the legend tab. On mobile devices, combining these tabs would thus create lots of scrolling.

**Comment by talltom** [comment]
- also there's an update which automatically drops down the first "how to report" video on the reports tab so this is less empty now than before.
