### ISSUE TITLE
Request to Add waterways to public map

### ISSUE THREAD

**Issue by anexact** [urbanriskmap/riskmap#218]
FY17Ext Dev Meeting Field Office 09 _ Request to ADD waterways, canals, pumps, etc. (as in REM)

**Comment by talltom** [comment]
@anexact - The base map tiles from mapbox have all waterways drawn and labelled. For public map should we just add pumps and other point features, as I worry adding waterways also will lead to confusing representations.

**Comment by anexact** [comment]
Yes, we could leave it out if too confusing, or add to legend with the option to turn on, as in previous PJ version? You're the map man, just one folks have asked us about in FO...

**Comment by talltom** [comment]
Will add as optional. Will add pumps and gates as on by default.

**Comment by anexact** [comment]
super.

**Comment by talltom** [comment]
Tag @asbarve 
https://docs.petabencana.id/routes/infrastructure.html

**Comment by talltom** [comment]
Moved this issue over to new Angular development: https://github.com/urbanriskmap/riskmap-ng/issues/7
