### ISSUE TITLE
REM Export Table update from BNPB

### ISSUE THREAD

**Issue by anexact** [urbanriskmap/riskmap#222]
FY17Ext Dev Meeting Field Office 13 _ following update meeting w/ BNPB, request for the "export table" on the REM so that agency directors can have a printout of counts for PR/media updates; suggest export interval count options of 1h, 6h, 12h, 24h, 3days, 7days. No map display needed, but a print button on this table would be appreciated by emergency staff.

**Comment by talltom** [comment]
@anexact - can you confirm what data to be exported?

I'm confused as how we would count flooded areas from REM, or are you talking about reports?

Thanks 👍

**Comment by anexact** [comment]
Nah, it was the PDC WYA suggestion of just using report counts as an export for Bandung and Surabaya since unlikely to see REM dev occur in those locations for long term.

**Comment by talltom** [comment]
OK, but to confirm - we would never show these data in a REM style interface - we would just provision an API for output so they could be consumed in CAP format by downstream users such as PDC, correct?

**Comment by anexact** [comment]
Correct.

**Comment by talltom** [comment]
This is now supported by https://github.com/urbanriskmap/cognicity-analytics
