### ISSUE TITLE
Different River Gauge symbol on REM & Public Map

### ISSUE THREAD

**Issue by prittandrani** [urbanriskmap/riskmap#226]
![image](https://user-images.githubusercontent.com/22338984/29503552-bc3b0c84-8662-11e7-9ec0-5eee0f1d74bc.png)

**Comment by talltom** [comment]
This has been fixed cognicity-rem (https://github.com/urbanriskmap/cognicity-rem/commit/1adb896cf71dfb5ec4245ac31f1cbf4037fa7b19) and pushed to dev stage.
