### ISSUE TITLE
Scalable library to add sensors data

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/riskmap#236]
- Client-server to hit single data api (eg. data.riskmap.us/sensors)
- Process fetched data, add map layers & style icons using specified thresholds
- Draw data charts
- Include link to source (eg. usgs / sfwmd)
* @talltom , add todo's for allied lambda's, schema, server changes in [meta repo](https://github.com/urbanriskmap/urbanriskmap-meta) or specific repos.

**Comment by talltom** [comment]
In-progress, but this is now being implemented in the new Angular project: https://github.com/urbanriskmap/riskmap-ng/commit/9be0a78a4c29d8c123ec2f1bb8a200abdfe27845
