### ISSUE TITLE
Update node/npm version for build

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/riskmap#246]
Any reason we can't use node v8.4.0 / npm v5.3.0 for building? I've gone with that version as it matches the version now used in cognicity-server builds and EB deployments. 
Notes:
* Also applies to cards (but I don't see the point opening an extra issue for that).
* Should document in package.json as well as configure jenkins builds.

**Comment by matthewberryman** [comment]
Just noting I've done this change for petabencana.id dev environment (main web site and cards) and seems fine.

**Comment by talltom** [comment]
@matthewberryman - sounds good, but need the green light from @ojha-url that he's happy using newer versions.

**Comment by ojha-url** [comment]
I think we already updated the node versions before Irma. Yesterday I received an npm msg to update to 5.5.1, so maybe take a call on that now...

**Comment by matthewberryman** [comment]
All updated to v8.4.0 / v5.3.0 (required for cards per https://github.com/urbanriskmap/cognicity-cards/issues/20 ) and working.
