### ISSUE TITLE
report flooding icon for dev

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/riskmap#247]
If we have dev bots set up, do we want that "report flooding" link to direct the user to report to the dev bots?

**Comment by abrahamq** [comment]
Yes I think so. How many changes would be required @mayank?

**Comment by asbarve** [comment]
@matthewberryman For India and US we don't have separate dev bots. those two instances are also being served from dev branch - We need to create new dev bots for both as well as make sure they have separate dev and production environment.

**Comment by ojha-url** [comment]
The deep links to bots are environment parameters, also dependent on deployment. Just the link needs to be changed as and when all bots are up.

**Comment by asbarve** [comment]
It should already be set up to take user to right bots I will check tomorrow

**Comment by asbarve** [comment]
Closing this issues - all dev versions are set up to take the users to relevant dev bots.
