### ISSUE TITLE
Create Dev bots for India and US.

### ISSUE THREAD

**Issue by asbarve** [urbanriskmap/riskmap#248]
Create Twitter, telegram, fb bots for testing - India and US
**RiskMap.in**
- ~Telegram~
- ~Facebook~
- Twitter

**Petabencana.id**

- ~Facebook~
-Facebook Prod Bot

**RiskMap.us**
- Telegram
- Facebook
- Twitter

**Comment by asbarve** [comment]
ANy update on this @abrahamq

**Comment by ojha-url** [comment]
**RiskMap.in**
- ~Telegram~
- Facebook
- Twitter

**RiskMap.us**
- Telegram
- Facebook
- Twitter
