### ISSUE TITLE
UI fix and consistancy for FB bots

### ISSUE THREAD

**Issue by asbarve** [urbanriskmap/riskmap#252]
-Add Buttons on US and PB facebook bots

**Comment by asbarve** [comment]
refer : https://developers.facebook.com/docs/messenger-platform/send-messages/persistent-menu

and 

button-template: https://developers.facebook.com/docs/messenger-platform/send-messages/template/button/

**Comment by ojha-url** [comment]
Move issue to FB lambda? or parent project

**Comment by asbarve** [comment]
@abrahamq any updates on this for Dev + Prod bots of Petabencana
