### ISSUE TITLE
info.petabencana.id safety issue

### ISSUE THREAD

**Issue by prittandrani** [urbanriskmap/riskmap#253]
cc @matthewberryman , when we tried to open info.petabencana.id recently it shows warning message like this:
![image](https://user-images.githubusercontent.com/22338984/32206717-6d9ae208-be29-11e7-88e6-421c3b47bb6e.png)

**Comment by matthewberryman** [comment]
The wordpress plugin for managing the cert is broken. I have fixed the certificate manually and have set up email reminders to prompt me in future (until the plugin is hopefully fixed).

**Comment by prittandrani** [comment]
thanks matthew for the quick fix!
