### ISSUE TITLE
non-GRASP reports don't show

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/riskmap#264]
https://www.petabencana.id/map/jakarta/74725
https://www.petabencana.id/map/jakarta/74687
https://www.petabencana.id/map/jakarta/74685

Reports don't load because the web client code expects a flood_depth field to be present which is not true for non-GRASP (e.g. qlue and detik) reports.

cc @prittandrani

**Comment by ojha-url** [comment]
Fixed via #265, #266, #267
