### ISSUE TITLE
PB.id map report flooding icon and language for pre-filled tweet

### ISSUE THREAD

**Issue by prittandrani** [urbanriskmap/riskmap#268]
Hi all! We noticed that the petabencana.id website has the report flooding icon like the riskmap.us one. May we suggest to change the wording and language:

- for the text below the icon, right now it is "Laporan Banjir", we suggest to change it to "**Laporkan Banjir**" (a clearer word to invite people to report)
- for the pre-filled tweet, currently it is in English and resulting in the card link message replied to the user is in English. We suggest to change it to Indonesian:
"**Laporkan banjir lewat @petabencana**". If the word "via" cannot be changed to "lewat", that will be fine.

cc @talltom @matthewberryman @asbarve @ojha-url 

Thank you! And just want to let you all know Jakarta and Bandung are having so much rain these days so looks like monsoon is on the way!

**Comment by asbarve** [comment]
- Changed the prefilled tweet in Bahasa to read as Laporkan Banjir via @petabencana 
- Cannot change 'via' however - "The attribution will appear in a Tweet as ” via @username” is translated into the language of the Tweet author"

**Comment by prittandrani** [comment]
thanks @asbarve !
