### ISSUE TITLE
fix Bahasa translations for info_content.intro - MIT Urban Risk Lab translated as "Humanitarian Infrastructures Group di MIT"

### ISSUE THREAD

**Issue by asbarve** [urbanriskmap/riskmap#287]
https://github.com/urbanriskmap/riskmap/blob/master/deployment_specific/pb/ds_locales/id.js

**Comment by fadmastuti** [comment]
done. also fixed some BI translation

**Comment by matthewberryman** [comment]
closing, will do separately in forked repo
